[package]
name = "cotton-ssdp"
version = "0.1.0"
authors = ["Peter Hartley <pdh@utter.chaos.org.uk>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neli = { version = "0.6", features = ["async"] }
tokio = { version = "1.0", features = ["macros"] }

[[example]]
name = "listener"
