[package]
name = "cotton-netif"
version = "0.0.1"
authors = ["Peter Hartley <pdh@utter.chaos.org.uk>"]
edition = "2021"
license = "CC0-1.0"

[dependencies]
tokio = { version = "1.18", default_features = false, features = ["macros", "sync", "rt"] }
bitflags = { version = "1.2", default_features = false }
futures-util = { version = "0.3", default_features = false }
async-stream = { version = "0.3", default_features = false }
nix = { version = "0.24", default_features = false, features = ["net"] }

[target.'cfg(target_os = "linux")'.dependencies]
neli = { version = "0.6", default_features = false, features = ["async"] }
