---
- name: dev packages
  hosts: all
  become: yes
  tasks:
  - name: apt
    apt:
      pkg:
      - emacs
      - yaml-mode

- name: sshd lockdown
  hosts: all
  become: yes
  tasks:
  - name: PubkeyAuthentication yes
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PubkeyAuthentication'
      line: 'PubkeyAuthentication yes'
  - name: PasswordAuthentication no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
  - name: ChallengeResponseAuthentication no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^ChallengeResponseAuthentication'
      line: 'ChallengeResponseAuthentication no'
  - name: UsePAM no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^UsePAM'
      line: 'UsePAM no'
  - name: No DSA key
    file:
      path: /etc/ssh/ssh_host_dsa_key
      state: absent
  - name: No DSA key
    file:
      path: /etc/ssh/ssh_host_dsa_key.pub
      state: absent
  - name: No ECDSA key
    file:
      path: /etc/ssh/ssh_host_ecdsa_key
      state: absent
  - name: No ECDSA key
    file:
      path: /etc/ssh/ssh_host_ecdsa_key.pub
      state: absent
  - name: Good ciphers
    lineinfile:
      path: /etc/ssh/sshd_config
      create: yes
      regexp: '^Ciphers'
      line: 'Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
  - name: Good MACs
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^MACs'
      line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
  - name: Good KexAlgorithms
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^KexAlgorithms'
      line: 'KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256'
  - name: AllowGroup ssh
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^AllowGroups'
      line: 'AllowGroups ssh _ssh'
  - name: PermitRootLogin no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
      validate: /usr/sbin/sshd -t -f %s

- name: laminar user
  hosts: all
  become: yes
  tasks:
  - name: create laminar group
    ansible.builtin.group:
      name: 'laminar'
      state: present
  - name: create laminar user
    ansible.builtin.user:
      name: 'laminar'
      password: '!'
      create_home: true
      group: 'laminar'
      shell: '/bin/bash'
  - name: 'create ~laminar/.ssh'
    file:
      path: /home/laminar/.ssh
      state: directory
      owner: laminar
      group: laminar
      mode: 0700
  - name: 'authorise laminar key'
    authorized_key:
      user: laminar
      key: "{{ lookup('file', 'laminar-ssh.pub') }}"

- name: pi setup
  hosts: all
  become: yes
  tasks:
  - name: disable SD polling
    lineinfile:
      path: /boot/firmware/config.txt
      regexp: '^dtparam=sd_poll_once'
      line: 'dtparam=sd_poll_once'
  - name: mark wifi optional
    copy:
      dest: /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
      content: |
        [Service]
        ExecStart=
        ExecStart=/lib/systemd/systemd-networkd-wait-online --any
