[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32F746ZGTx"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]
target-dir = "target-arm" # To match what the outer Cargo's build.rs does
